name: fanney
favicon: null
layout_spectrum: 0.4501978727057576
typography_spectrum: 0.635054609272629
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.21661836747080088
  lightness: 0.36048003123141825
  saturation: 0.9950906645972282
  rhythmicContrast: 0.319222069112584
purpose: []
